name: Create an SSH Session to an EC2 instance via SSM
description:
  Establishes an SSH connection to EC2 via SSM using AWS SDK without having to
  setup SSH keys
author: Bond

branding:
  icon: terminal
  color: gray-dark

inputs:
  ec2-instance-id:
    description: 'EC2 Instance ID to connect to.'
    required: true
  remote-user:
    description: 'Remote user for SSH (e.g., ubuntu, ec2-user).'
    required: true
  aws-region:
    description:
      'AWS Region of the EC2 instance and SSM. Defaults to the same region your
      AWS Authentication tokens are in'
    required: false

runs:
  using: node20
  main: dist/index.js
  post: dist/cleanup/index.js
